[wokwi]
version = 1
firmware = '.pio/build/chamber-controller-wokwi/firmware_merged.bin'
elf = '.pio/build/chamber-controller-wokwi/firmware.elf'

# firmware = '.pio/build/chamber-controller-wokwi/firmware.bin'
# elf = '.pio/build/chamber-controller-wokwi/firmware.elf'
# gdbServerPort = 3333

# [[net.forward]]
# from = "localhost:8180"
# to = "target:80"
