name: PlatformIO CI

on: 
  pull_request:
  push:
    branches: 
      - main
      - dev

jobs:
  pio-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Checkout UI
        run: |
          echo "Checkout UI"
          git clone https://github.com/mp-se/chamber-controller-ui chamber-controller-ui 
          cp chamber-controller-ui/dist/assets/style.css.gz html/app.css.gz
          cp chamber-controller-ui/dist/assets/index.js.gz html/app.js.gz

      - name: Setup PlatformIO
        uses: n-vr/setup-platformio-action@v1.0.1    
  
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1
        with:
          environments: "chamber-controller-32,chamber-controller-s2"
          #project-dir: "./some_dir"
          #project-conf: "./some_dir/custom.ini"
          jobs: 6
          silent: false
          verbose: true
          disable-auto-clean: false

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version. https://github.com/marketplace/actions/add-commit
        if: ${{ github.event_name != 'pull_request' }}
        with:
          add: 'bin html'
          author_name: GitHub Action
          author_email: mp-se@noreply.github.com
          default_author: github_actor
          message: 'GitHub Action Build'
          pathspec_error_handling: ignore

