name: PlatformIO CI

on: 
  pull_request:
  push:
    branches: 
      - main
      - dev

jobs:
  pio-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
    
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build UI
        working-directory: ui
        run: |
          npm install
          npm run build
          cd ..
          ./copy_ui.sh

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          python -m pip install platformio intelhex

      - name: PlatformIO Run
        run: |
          pio run \
            --environment chamber-controller-32pro \
            --environment chamber-controller-s2 \
            --environment chamber-controller-s3 \
            --jobs 6 \
            --verbose

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version. https://github.com/marketplace/actions/add-commit
        if: ${{ github.event_name != 'pull_request' }}
        with:
          add: 'bin html'
          author_name: GitHub Action
          author_email: mp-se@noreply.github.com
          default_author: github_actor
          message: 'GitHub Action Build'
          pathspec_error_handling: ignore
